# Generated by Django 4.0 on 2023-10-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicycle',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
