# Generated by Django 4.0 on 2023-10-22 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_bicycle_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicycle',
            name='slug',
        ),
    ]
