# Generated by Django 4.0 on 2023-10-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='count_product',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
