# Generated by Django 4.0 on 2023-10-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_rename_count_product_cart_quantity_alter_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_order',
            field=models.BooleanField(default=False),
        ),
    ]
